import { Team } from './team';

export const TEAMS: Team[] = [
    {name: 'Arizona Cardinals', founded: 1920, location: 'Tempe, Arizona', website: 'azcardinals.com'},
    {name: 'Atlanta Falcons', founded: 1966, location: 'Atlanta, Georgia', website: 'atlantafalcons.com'},
    {name: 'Baltimore Ravens', founded: 1996, location: 'Baltimore, Maryland', website: 'baltimoreravens.com'},
    {name: 'Buffalo Bills', founded: 1960, location: 'Buffalo, New York', website: 'buffalobills.com'},
    {name: 'Carolina Panthers', founded: 1995, location: 'Charlotte, North Carolina', website: 'panthers.com'},
    {name: 'Chicago Bears', founded: 1920, location: 'Chicago, Illinois', website: 'chicagobears.com'},
    {name: 'Cincinnati Bengals', founded: 1968, location: 'Cincinnati, Ohio', website: 'bengals.com'},
    {name: 'Cleveland Browns', founded: 1946, location: 'Cleveland, Ohio', website: 'clevelandbrowns.com'},
    {name: 'Dallas Cowboys', founded: 1960, location: 'Dallas, Texas', website: 'dallascowboys.com'},
    {name: 'Denver Broncos', founded: 1960, location: 'Denver, Colorado', website: 'denverbroncos.com'},
    {name: 'Detroit Lions', founded: 1930, location: 'Detroit, Michigan', website: 'detroitlions.com'},
    {name: 'Green Bay Packers', founded: 1921, location: 'Green Bay, Wisconsin', website: 'packers.com'},
    {name: 'Houston Texans', founded: 2002, location: 'Houston, Texas', website: 'houstontexans.com'},
    {name: 'Indianapolis Colts', founded: 1953, location: 'Indianapolis, Indiana', website: 'colt.com'},
    {name: 'Jacksonville Jaguars', founded: 1995, location: 'Jacksonville, Florida', website: 'jaguars.com'},
    {name: 'Kansas City Chiefs', founded: 1960, location: 'Kansas City, Kansas', website: 'chiefs.com'},
    {name: 'Los Angeles Chargers', founded: 1960, location: 'Los Angeles, California', website: 'chargers.com'},
    {name: 'Los Angeles Rams', founded: 1937, location: 'Los Angeles, California', website: 'therams.com'},
    {name: 'Miami Dolphins', founded: 1966, location: 'Miami, Florida', website: 'miamidolphins.com'},
    {name: 'Minnesota Vikings', founded: 1961, location: 'Minneapolis, Minnesota', website: 'vikings.com'},
    {name: 'New England Patriots', founded: 1960, location: 'Foxborough, Massachusetts', website: 'patriots.com'},
    {name: 'New Orleans Saints', founded: 1967, location: 'New Orleans, Louisiana', website: 'neworleanssaints.com'},
    {name: 'New York Giants', founded: 1925, location: 'New York, New York', website: 'giants.com'},
    {name: 'New York Jets', founded: 1960, location: 'East Rutherford, New Jersey', website: 'newyorkjets.com'},
    {name: 'Oakland Raiders', founded: 1960, location: 'Oakland, California', website: 'raiders.com'},
    {name: 'Philadelphia Eagles', founded: 1933, location: 'Philadelphia, Pennsylvania', website: 'philadelphiaeagles.com'},
    {name: 'Pittsburgh Steelers', founded: 1933, location: 'Pittsburgh, Pennsylvania', website: 'steelers.com'},
    {name: 'San Francisco 49ers', founded: 1946, location: 'San Francisco, California', website: '49ers.com'},
    {name: 'Seattle Seahawks', founded: 1976, location: 'Seattle, Washington', website: 'seahawks.com'},
    {name: 'Tampa Bay Buccaneers', founded: 1976, location: 'Tampa, Florida', website: 'buccaneers.com'},
    {name: 'Tennessee Titans', founded: 1960, location: 'Nashville, Tennessee', website: 'titansonline.com'},
    {name: 'Washington Redskins', founded: 1932, location: 'Washington D.C.', website: 'redskins.com'}
]